language: cpp

os: linux

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
      env: CXX=g++-7 CC=gcc-7

branches:
  only:
    - master

script: 
  - ./installBoost.py --version 1.61.0 /tmp/apps/boost/1.61.0
