language: cpp

os: linux

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
            - python-jinja2
            - build-essential 
            - libxmu-dev
            - libxi-dev 
            - libgl-dev
      env: CXX=g++-7 CC=gcc-7

branches:
  only:
    - master

script: 
  - ./installAll.sh /tmp/apps/
